### ISSUE TITLE
CurveImpl.MPA_RTC is not considered during tests

### ISSUE THREAD

**Issue by matyesz** [NetCal/DiscoDNC#1]
Although it is set to use both CurveImpl types, tests only use the default (DNC) value.

**Comment by NetCal** [comment]
I can confirm this issue. The fix is to add
	CalculatorConfig.getInstance().setCurveImpl(test_config.getCurveImpl());
to the DncTest.java's initializeTest(...) method.

The same problem issue applies to setting the number representation.

Both issues are fixed in rev 8bf764e, tests are all green.
