### ISSUE TITLE
Do Not Duplicate DNC LinearSegment Class

### ISSUE THREAD

**Issue by sbondorf** [NetCal/DiscoDNC#12]
While investigating issue #11, I thought about current and future code sharing between curve.dnc_affine and curve.dnc_pwaffine. Methods in the respective curve classes will definitely diverge, yet, I do not think that the rather simplistic LinearSegment class ever will. Thus, I suggest sharing it between both implementations. To do so, an adaptation our package hierarchy probably best:
- curve.dnc_affine --> curve.dnc.affine 
- curve.dnc_pwaffine --> curve.dnc.pwaffine

such that the LinearSegment class we maintain can be moved into package curve.dnc

**Comment by phschon** [comment]
What else would be in the dnc package? I think nothing else. Thus I would propose to just move the LinearSegment up one level into the curves package (although this class is not used in all curves).

**Comment by sbondorf** [comment]
So far, the top-level curve package only consists of interfaces. These might implement some convenient static methods only relying on methods they define. Any implementation of the interfaces is, however, in packages underneath de.uni_kl.discodnc.curve, packages that should name the developer (dnc or mpa_rtc). This was not (yet) defined as a strict requirement but I feel we should keep it as this separation of interfaces and implementations results in a clearer structure.

**Comment by phschon** [comment]
As I see @matyesz has already create PR #14 for this issue. Thanks.
