### ISSUE TITLE
Tests: Extract Expected Results from Test Classes

### ISSUE THREAD

**Issue by NetCal** [NetCal/DiscoDNC#15]
Goal: Reduce code duplication of extensions that come with adapted test arguments.

Challenge: The test results need to know the flows in the test network in order to map the correct results to them. Moreover these results might also change, depending on the analysis config (i.e., not only the analysis itself).
Thus, a test class must instantiate its network and the results classes correctly before executing the actual tests it defines.

**Comment by sbondorf** [comment]
I am working on this feature in the [test_results_separation](/sbondorf/DiscoDNC/tree/test_results_separation) branch in my DiscoDNC fork. See also the issues I opened there.
