### ISSUE TITLE
Make main/tests transitive from DiscoDNC to dependent projects

### ISSUE THREAD

**Issue by matyesz** [NetCal/DiscoDNC#17]
Tests should not be copied through dependent projects but should be available as a dependency.

**Comment by sbondorf** [comment]
The motivation for this is to solve NetCal/DiscoDNCext_MPARTC#6, I guess.

I do have another point in favor of this idea.
We currently only provide tests for small networks that cover basic compositions of algebraic operations. For these networks, expected results were computed manually.
In addition, I would like to add a set of tests consisting of larger, considerably more complex networks that test against the results of previous DiscoDNC versions. This is mostly targeted at testing tool feature (on contrast to DNC computations) such as convolution of alternative arrival bounds or a cache for intermediate results (see [1]). Yet, the networks used in [1] already come at a size of 37MB.

[1] Quality and Cost of Deterministic Network Calculus – Design and Evaluation of an Accurate and Fast Analysis (Steffen Bondorf, Paul Nikolaus, Jens B. Schmitt), In Proceedings of the ACM on Measurement and Analysis of Computing Systems (POMACS), ACM, volume 1, 2017.

**Comment by matyesz** [comment]
//Pure junit5 test suite
@ExtendWith(TestTimer.class)
@SelectClasses({LinkedListTest_add.class, LinkedListTest_remove.class})
public class LinkedListTest {

    @BeforeAll
    public void beforeAll() {
        ...
    }

    @AfterAll
    public void afterAll() {
        ....
    } 
}

**Comment by matyesz** [comment]
Investigation done. Results:
junit5 does not support test suites at the moment but junit4  launcher does not run junit5 annotated test cases. We have 2 possibilities:
1. We create a test jar and add dependency to extension as mentioned above. In this case test classes will be visible but must be extended by a class to be ran. It is easy to implement but not too nice and we still will have duplicates.
2. We create a multimodule project with one common test module. This way we can build and release the core and extensions together and run common tests on them stored in a separate module. As I se the tests are anyway rather integration tests than junit.
Parent module
    Core
    Ext1
    Ext2
    Integration test

What do you think?

**Comment by sbondorf** [comment]
If Maven's multi module capabilities automate assembly of Core and extensions in order to run the tests (that is how I understand it), I am in favor of this alternative.
That will work with locally installed extensions as well, right? As the MPA RTC toolbox is not in the Maven Central Repository, we will not be able to push the extension there either.

**Comment by matyesz** [comment]
Yes, when maven does the build it will compile both core and extension then runs integration tests automatically. If mvn test is ran the same happens. But you will also be able to build the projects separately with their own jinit test in this case integration tests are not ran.
It will if a perant pom is added and the test module is installed next to the extension. Core can be just a dependency.

**Comment by matyesz** [comment]
Could you create repositories for tests and the parent?

**Comment by sbondorf** [comment]
Sure.
https://github.com/NetCal/DiscoDNC_tests
https://github.com/NetCal/DiscoDNC_meta (naming is inspired by linux distribution package naming)

**Comment by sbondorf** [comment]
Refactoring complete after these pull requests:
https://github.com/NetCal/DiscoDNC/pull/19
https://github.com/NetCal/DiscoDNC_tests/pull/2
https://github.com/NetCal/DiscoDNCext_MPARTC/pull/7

**Comment by sbondorf** [comment]
There's still a branch called #17_make_tests_transitive. Can we delete it?
