### ISSUE TITLE
Inconsistent Naming of Specialized Classes

### ISSUE THREAD

**Issue by sbondorf** [NetCal/DiscoDNC#27]
As we are currently adding code that is specialized to certain curve shapes (Affine and PwAffine), we seem to have silently decided that is is not enough to place the according interface implementations (classes) in a separate and reasonably named package. We also vary the class name by a prefix and/or suffixes to include all the specializations. Imho, this is not a problem. Yet, we do so in an inconsistent way. I would like to agree on a common naming convention to be implemented before the first release of specialized code.

Here are my observations (probably also introduced by me):
* Affine curves in de.uni_kl.cs.discodnc.curves.dnc.affine use an "Affine" prefix while affine min-plus-operators in de.uni_kl.cs.discodnc.minplus.dnc.affine use an "affine" suffix.
* DNC PwAffine implementations (curve or operators) neither use a prefix nor a suffix. I think this signals that PwAffine is the most generic curve shape, which it isn't. For example, see MPA RTC extension where Curve classes have a "_PwAffine" suffix because this is actually a restriction to the MPA RTC capabilities.

I recommend to:
* Only use suffixes.
* Compose the suffixes of "_" + "Affine" or "PwAffiine".
This is reversing the relevant last part of the package name, just like the first part of it reverses our domain name.

**Comment by phschon** [comment]
For the sake of completeness, there is more to be considered:

- the enum entries in the `minplus` package and `CurveBackend*` also contian "AFFINE" suffixes (although they seem to fit your recommendation)
- the classes in `minplus.dnc.affine" should have an underscore and capital "A" according to the above mentioned recommendation instead of the current suffix
- the classes in `minplus.dnc.pwaffine` should be renamed

- (minor: PwAffine should be written with only one "i")

**Comment by sbondorf** [comment]
Thanks for completing and pointing out the typo.
I had another look at the code but did not find any further occurrences that we need to adapt to this naming convention.

**Comment by phschon** [comment]
Regarding your recommendation, I would approve the convention.
However, as a sidenode, a prefix would increase the readability. E.g. `Affine_ArrivalCurveDNC.java` instead of `ArrivalCurveDNC_Affine.java`. Nevertheless, I think a suffix is the better way.
