### ISSUE TITLE
Rework of Repository and File Structure

### ISSUE THREAD

**Issue by phschon** [NetCal/DiscoDNC#29]
@sbondorf and I discussed a potential rework of the current code and repository structure. Imho the current state of having 4 repositories that are needed to compile the DiscoDNC, without references to each other, is not very intuitive. Moreover specific compile instructions are missing. Thus I would like to restructure the repositories and rebuild the original and more intuitive package structure. @matyesz, I would like to discuss the following idea.

Basic Idea:
Rebuild the original hierarchy, with the core DNC code contained in this repository in `src/main/java`, the tests in `src/test/java` and the MPA extension in `src/mpa_ext/java`, while the code of the latter ones is still kept in their respective repositories.

In order to achieve this, git submodules are used to create a reference to the respective repository in `src/mpa_ext` and `src/test`. The two repositories will only contain the packages that contain the code an fit in the proposed hierarchy. When checking out the core repository the respective submodules can be added as needed, since they are not automatically included.

The only `pom.xml` will be found in this repository, including two profiles. One for adding the mpa extension to a compiled jar and one for creating an additional jar for the tests. Since there is no point in compiling those two parts without the core code, there is no need for additional poms.

The meta repository will become obsolete.

The resulting file structure looks like this:
```
DiscoDNC repository
| - pom.xml
| - src
    | - main/java/... (core code)
    | - mpa_ext (submodule/reference to the mpa_ext repository)
        | - java/... (mpa wrapper code contained in the DiscoDNCext_MPARTC repository)
    | - test (submodule/reference to the DiscoDNC_tests repository)
        | - java/... (test classes)
| - ... other files in this repository
```

The benefits of this structure:
- reference on each repository
- easy to checkout/each submodule can be added when needed
- only one pom including profiles for including each submodule
- easy to compile, no parent dependencies to files that are not included in the repository
- intuitive package hierarchy

For testing purposes I created private repositories that represent the above structure using a small set of classes and packages. I can provide access if you want to have a look at it.

**Comment by matyesz** [comment]
You can also have a similar structure with maven submodules too, although it will need a corresponding directory structure. If I understand well in this case mpa_ext/java will be the extension package source.
Test should be in this case a mandatory submodule, as this must be run always before commiting a new change:). I see the benefits of this hierarchy and do not see any disadvantages at the moment. Agreed. Perhaps the profiles should be used to have a core and mpa_ext build. Tests should be a total different jar if we want to release them. I would rather prefer just releasing the demos not the junit tests. If the core jar is released to maven repo, it can be used by anybody to write a new extension without changing our code. Testing the extension must be done by the one who extended, not our junit tests. Seems the testing will be the next refactoring again, to enable extension to use some base classes from discoDNC junit tests.

**Comment by phschon** [comment]
The tests will be compiled in a seperate jar. However, I would not make them mandatory, since not everyone using the core code (or checking out the repository) will need them.

There will be a profile that includes the mpa extension in the jar containinig the core code, e.g. `mvn package -P mpa` (as well as a similar one for a test jar). The default profile will only compile the core code.

**Comment by matyesz** [comment]
Checked the pros and contras on several blogs. What we win on build simplicity, we will loose on version handling. Commit, push and pull is not automatic for submodules so that part will need an extra description and some alis binding on local git. Otherwise revisions can be quickly messed up. Anyway everything has its own price :).

**Comment by phschon** [comment]
Correct. However, I thought that, since each submodule has it's own repository (ofc), they must be seperately developed and maintained anyway.
If @sbondorf is fine with this structure I will proceed with reworking the repositories.

**Comment by matyesz** [comment]
Agreed. No opposition from my side.

**Comment by sbondorf** [comment]
If you are both agreeing from a technical perspective, please go ahead with implementing this structure. I would only veto if the structure caused problems with publishing the DiscoDNC core in the Maven Central Repository.
Please do not forget to integrate the NetCal/DiscoDNC_experiments repository.

**Comment by phschon** [comment]
Well, I encountered a first problem: Neither IntelliJ nor maven can find the `org.junit.platform:junit-platform-surefire-provider:1.2.0` depedency, although I tried copying it from the old pom and from the maven repository page. I am still not able do get this one in my local repository. I am pretty sure that it worked in previous versions and the DiscoDNC_tests repository. Do you have any suggestions or help?

```
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-surefire-provider</artifactId>
    <version>1.2.0</version>
    <scope>test</scope>
</dependency>
```

**Comment by matyesz** [comment]
Perhaps deleting your local maven repo and restarting a full maven vuild cycle. It is still on te maven central repo.

**Comment by phschon** [comment]
Merged and closed by now.
