### ISSUE TITLE
Curve Interface Hierarchy

### ISSUE THREAD

**Issue by NetCal** [NetCal/DiscoDNC#3]
Currently, the generic Interfaces for ArrivalCurve, ServiceCurve and MaxServiceCurve extend CurvePwAffine. I.e., they are in the third level of the hierarchy (see attached image taken from the ECRTS Paper of @phschon and @sbondorf). Thus they carry information about semantics and shape. They should move one level up. Then, for example, a piece-wise affine arrival curve has to implement the interfaces ArrivalCurve and PwAffineCurve.

![uml_curve_hierarchy_white](https://user-images.githubusercontent.com/29837309/38004264-0eda1ff4-326e-11e8-90d5-b347319797cf.png)

**Comment by sbondorf** [comment]
After merging #5 into the v2.5 branch, we have the desired hierarchy. Yet, the PMOO left-over service curve that uses affine curves internally will now always create instances of our DNC curves to work with. Thus, we do not have an MPA-RTC-only code path. Can we bring this feature back by letting CurvePwAffine extend CurveAffine and replace curves.dnc_affine.AffineCurve_DNC with curves.CurveAffine in the PMOO analysis?

**Comment by matyesz** [comment]
Let me check this, when I introduced AffineCurves next to original PWAffineCurves with DNC a lot of tests started to fail with calculations using AffineCurves. Is that OK?
