### ISSUE TITLE
Add source directories to maven pom.xml in v2.5

### ISSUE THREAD

**Issue by matyesz** [NetCal/DiscoDNC#32]
Without this change maven will not compile new source directories.
pom.xml needs a bit more refactoring:
1. integration tests must run with each build with each profile, not just with tests profile build
2. version numbers must be fixed
3. unit tests must run with each profile build
4. introducing variables for junit version numbers
5. cleanup tests profile
6. adding java 10 as compiler
7. do we want separate jars for each? test, mpa_ext and exp? We also need to define jar names

**Comment by sbondorf** [comment]
This is about the pom in the v2.5 branch, right? Maybe you can label the issue accordingly.

Thanks for investigating issues and improvements! These are my thoughts:
2. These are the version numbers of dependencies, not the DiscoDNC and submodules, right? A quick look revealed an inconsistency with the maven-surefire-plugin in different profiles. Is there more?
3. From a technical perspective, does it make sense to add unit test-related xml tags without providing unit tests?
4. How would these variables look like? We have a lower bound on the JUnit version: We need at least version 5.2.0 due to the method source annotation. Pulling newer versions should be fine, yet, JUnit also puts milestones and release candidates into the Maven Repo. We do not want those and I was not able to figure out how to make that clear in the pom.xml file.
7. I like the separate jars. My workflow often involves creating a jar, copying it to a remote server and running it there. Depending on the Internet connection where I am at this time, having to copy an all-encompassing DiscoDNC jar that bundles unused tests (+documentation PDFs) and experiments can be (and already had been) a pain.
Regarding the naming: None of the submodules can work stand alone. Therefore, I suggest to just use the submodule name. Is that ok?

**Comment by matyesz** [comment]
Please see the answers attached to the question:

This is about the pom in the v2.5 branch, right? Maybe you can label the issue accordingly.
Done

Thanks for investigating issues and improvements! These are my thoughts:
2. These are the version numbers of dependencies, not the DiscoDNC and submodules, right?
Yes, the version numbers of maven dependencies (junit, surefire ...) A quick look revealed an inconsistency with the maven-surefire-plugin in different profiles. Is there more?
Yes, source directories are not imported in development environments automatically, jars are not created during different builds... Original pom was OK as a starter but not as a final solution.
3. From a technical perspective, does it make sense to add unit test-related xml tags without providing unit tests?
JUnit is also used for functional tests (I had to rename them to integration tests as maven gives full aoutomated support for integration testing - see mvn verify vs mvn test). Technically it does not have sense at the moment but perhaps later someone can introduce a junit test for one of the classes, who knows...
4. How would these variables look like? We have a lower bound on the JUnit version: We need at least version 5.2.0 due to the method source annotation. Pulling newer versions should be fine, yet, JUnit also puts milestones and release candidates into the Maven Repo. We do not want those and I was not able to figure out how to make that clear in the pom.xml file.
I have introduced variables and will provide a solution for later auto upgrades.
7. I like the separate jars. My workflow often involves creating a jar, copying it to a remote server and running it there. Depending on the Internet connection where I am at this time, having to copy an all-encompassing DiscoDNC jar that bundles unused tests (+documentation PDFs) and experiments can be (and already had been) a pain.
Will do, I have the following in my mind:
1, DiscoDNC jar - classes and sources of the core functionality (no tests, no extensions, no experiments)
2, DiscoDNC_ext.jar - classes and sources of the extension functionality (no tests, no experiments) (we should decide whether to use the core as dep. from the maven repo or add it as classes to the jar)
3, DiscoDNC_tests.jar - classes and sources of the tests  (no experiments) (we should decide whether to use the core and extentsion as dep. from the maven repo or add it as classes to the jar)
4, DiscoDNC_experiments.jar - classes and sources of the experiments functionality (no experiments) (we should decide whether to use the core and extension as dep. from the maven repo or add it as classes to the jar)
Regarding the naming: None of the submodules can work stand alone. Therefore, I suggest to just use the submodule name. Is that ok?
Sure, wil ldo it like that.

**Comment by matyesz** [comment]
Automatically importing source directories, does that replace the manual git submodule update mentioned in the README.md?
No, that is a git alias that must be done, I can add that too. It will ensure that src directories will be added to eclipse build path.

If needed we can add rtc.jar to the maven build but in that case you cannot upload the core to the maven repo I think. During runtime you can put rtc.jar anywhere java will use it from the classpath.

Maven will do the exact same jars as eclipse, they will be executable, just the rtc.jar must be added to the classpath.

We can introduce OSGI behaviour to have plugins and tests collect all existing plugins but does it have any sense for just integration tests? OSGI gives a lot of execution overhead during startup. What we could do is to check the classpath during execution for given jars. In case of tests I can accept some hardcoded jar names.

**Comment by sbondorf** [comment]
> If needed we can add rtc.jar to the maven build but in that case you cannot upload the core to the maven repo I think. During runtime you can put rtc.jar anywhere java will use it from the classpath.

I do not see a need for rtc.jar in the core. Am I missing something? Code in the core does not depend on the rtc.jar so we should be fine, right?
Just the extension and the test will not be in the repo. I consider those to be interesting for core-developers only. Having these parts in github is be sufficient in my opinion; demanding to get the rtc.jar is not a pain either.
I think that the main purpose of the Maven repo is to alleviate use of the DiscoDNC core, not development on it. I.e., other projects that may want to apply network calculus are most certainly fine with just getting the core and are happy to get it from the Maven repo as a dependency.

> Maven will do the exact same jars as eclipse, they will be executable, just the rtc.jar must be added to the classpath.

Developers will get along. So do researchers who want to try this curve backend. Most probably, people will use the double precision float backend anyway.

> We can introduce OSGI behaviour to have plugins and tests collect all existing plugins but does it have any sense for just integration tests? OSGI gives a lot of execution overhead during startup.

I think that is decisive for not using OSGi. Indeed, I once had a look and thought of it to be too complex.

> What we could do is to check the classpath during execution for given jars. In case of tests I can accept some hardcoded jar names.

This should go into a separate issue. I will create one.
But let me ask one additional question here: Can we relax the hardcoded jar names to a specific pattern that indicates capabilities (i.e., implemented interfaces)? For example, the pattern could be {short interface path/name}-{plugin name}.jar and RTC MPA code would then be in curve_CurvePwAffine-MPA_RTC.jar. We only hardcode the package prefix "de.uni_kl.cs.discodnc." in our code, the remainder is found in the jar name. We refer to the sub-package "curve", and implement interface CurvePwAffine (indicated by capital letter in the front). The name of our implementation is MPA_RTC and all the code needs to be in the de.uni_kl.cs.discodnc.curve package (this last point is subject to more refinement).

**Comment by sbondorf** [comment]
This is left over from the referenced pull request:
> Another, a different question: Is there a way to remove the general JUnit dependency from pom.xml. We only need it for the tests, right? Yet moving it to that profile caused my Eclipse to complain about unresolvable dependencies ... Is that Eclipse-specific again or is this a problem to work around for mvn (command line) and IntelliJ, too?

Can somebody provide me with some insights on this?

**Comment by matyesz** [comment]
Yes, if it is a full separate project that can be used by itself and can be published to maven, it should be rather a dependency than an include.

**Comment by matyesz** [comment]
This is left over from the referenced pull request:

Another, a different question: Is there a way to remove the general JUnit dependency from pom.xml. We only need it for the tests, right? Yet moving it to that profile caused my Eclipse to complain about unresolvable dependencies ... Is that Eclipse-specific again or is this a problem to work around for mvn (command line) and IntelliJ, too?
 
It is a test dependency so wil lnot bother runtime. Will resolve after my changes. I do not have this issue in my eclipse.

**Comment by sbondorf** [comment]
> Yes, if it is a full separate project that can be used by itself and can be published to maven, it should be rather a dependency than an include.

I moved forward with this. After some improvements to the NumBackend that were only applied in the new repository, I released v1.0 of it. I packaged this version, removed the DiscoDNC's bundled one and added the NumBackend-1.0 jar as a system dependency (for now, will change when moving to Maven Central repo). This is the pull request #36.

**Comment by sbondorf** [comment]
Is this done after pull request #37 was merged in commit 91e5f6e110e5f48b3e99db37535065b710a9ea74?
